spring.application.name=cinema-management
server.servlet.context-path=/cinema-management

spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_management
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect